import os
import json
import pathlib
import logging
from google import genai
from google.genai import types
from pydantic import BaseModel
from typing import List
from sqlalchemy.orm import Session
from .. import schemas, models

# Setup uvicorn error logging for FastAPI console visibility
logger = logging.getLogger("uvicorn.error")

# Manual dotenv loader to read environment variables from a .env file securely
def load_dotenv():
    # Look for .env in current working directory, backend/ and project root parent directories
    for folder in [
        pathlib.Path.cwd(), 
        pathlib.Path(__file__).parent.parent.parent, 
        pathlib.Path(__file__).parent.parent.parent.parent
    ]:
        for filename in [".env", "backend/.env"]:
            path = folder / filename
            if path.exists():
                try:
                    with open(path, "r", encoding="utf-8") as f:
                        for line in f:
                            line = line.strip()
                            if line and not line.startswith("#") and "=" in line:
                                key, val = line.split("=", 1)
                                os.environ[key.strip()] = val.strip().strip('"').strip("'")
                except Exception as e:
                    print(f"Error loading env file {path}: {e}")

load_dotenv()

# Pydantic schema for Gemini structured JSON response
class StoryPageResponse(BaseModel):
    page_number: int
    text: str
    visual_prompt: str

class StoryResponseSchema(BaseModel):
    title: str
    pages: List[StoryPageResponse]


def clean_story_title(title: str, request: schemas.StoryGenerateRequest, is_gemini_generated: bool = False) -> str:
    if not title:
        return ""
    
    title = title.strip()
    
    if request.custom_title:
        return request.custom_title

    # If it is generated by Gemini, keep it exactly as-is!
    if is_gemini_generated:
        return title

    # If title starts with "Story about ", check if we should keep the prefix
    if title.lower().startswith("story about "):
        topic = title[12:].strip()
        standard_topics = {
            "going to the dentist",
            "getting a haircut",
            "sharing toys at school",
            "sharing toys with friends",
            "custom situation",
            "new situation"
        }
        if topic.lower() in standard_topics:
            return title
        return topic

    # If it does not start with "Story about ", check if we should prepend it
    # We only prepend "Story about " if the title is one of the generic/standard ones
    standard_topics = {
        "going to the dentist",
        "getting a haircut",
        "sharing toys at school",
        "sharing toys with friends",
        "custom situation",
        "new situation"
    }
    if title.lower() in standard_topics:
        return f"Story about {title}"
        
    return title


def _generate_mock_social_story(db: Session, request: schemas.StoryGenerateRequest, source: str = "fallback") -> schemas.StoryCreate:
    """Fallback generator producing predictable mock social stories locally."""
    situation_title = "New Situation"
    situation_desc = ""
    
    if request.situation_id:
        db_situation = db.query(models.Situation).filter(models.Situation.id == request.situation_id).first()
        if db_situation:
            situation_title = db_situation.title
            situation_desc = db_situation.description
            
    if request.custom_situation_text:
        # If both are provided, let's use the custom text as description
        if not request.situation_id:
            situation_title = "Custom Situation"
        situation_desc = request.custom_situation_text

    if request.custom_title:
        situation_title = request.custom_title

    # Formulate a natural first-person introduction on Page 1 integrating the child's name and age if provided
    intro_sentences = []
    if request.child_name and request.child_age:
        intro_sentences.append(f"My name is {request.child_name} and I am {request.child_age} years old.")
    elif request.child_name:
        intro_sentences.append(f"My name is {request.child_name}.")
    elif request.child_age:
        intro_sentences.append(f"I am {request.child_age} years old.")
    
    intro_prefix = " ".join(intro_sentences) + " " if intro_sentences else ""
    
    title = clean_story_title(situation_title, request)
    pages = []
    
    title_lower = situation_title.lower()
    
    if "dentist" in title_lower:
        pages = [
            {
                "page_number": 1, 
                "text": f"{intro_prefix}Today, I am going to visit the dentist. The dentist is a friendly helper who helps keep my teeth clean and strong.", 
                "visual_prompt": "A friendly dentist smiling and holding a giant cartoon tooth model"
            },
            {
                "page_number": 2, 
                "text": "When we arrive, I will sit in a special big chair. The chair can go up and down like a slow, fun ride.", 
                "visual_prompt": "A child sitting happily in a large adjustable dentist chair"
            },
            {
                "page_number": 3, 
                "text": "The dentist will shine a bright light to look at my teeth. If the light feels too bright, I can choose to wear cool sunglasses.", 
                "visual_prompt": "A child wearing green sunglasses, smiling under a circular dental light"
            },
            {
                "page_number": 4, 
                "text": "They will use a tiny mirror and a small brush to clean my teeth. The brush might tickle my gums or hum like a bee.", 
                "visual_prompt": "A hand holding a tiny tooth mirror and a soft electric toothbrush"
            },
            {
                "page_number": 5, 
                "text": "If I feel worried or need a break, I can choose to raise my hand. The dentist can pause, and we can take a slow, deep breath together.", 
                "visual_prompt": "A child raising their hand with a calm smile, the dentist nodding respectfully"
            }
        ]
    elif "haircut" in title_lower or "hair" in title_lower:
        pages = [
            {
                "page_number": 1, 
                "text": f"{intro_prefix}Today, I am getting my hair trimmed. Getting a haircut helps my hair look neat and stay out of my eyes.", 
                "visual_prompt": "A smiling child looking at their hair in a mirror"
            },
            {
                "page_number": 2, 
                "text": "I will sit in a tall chair and wear a soft cape. The cape works like an umbrella to help keep loose hairs off my clothes.", 
                "visual_prompt": "A child wearing a colorful cape, sitting in a barber chair"
            },
            {
                "page_number": 3, 
                "text": "The hairstylist will spray a little water to make my hair damp. It can feel like a cool, gentle mist.", 
                "visual_prompt": "A hand holding a spray bottle creating a light water mist"
            },
            {
                "page_number": 4, 
                "text": "I will hear the snip-snip of scissors and the soft hum of clippers near my ears. I can choose to hold my favorite toy or take deep breaths to feel safe.", 
                "visual_prompt": "Barber scissors cutting hair, child hugging a plush bear toy"
            },
            {
                "page_number": 5, 
                "text": "I can try to keep my head still like a quiet statue. When we are finished, my hair will feel neat and I can feel proud.", 
                "visual_prompt": "A child with a fresh haircut smiling, holding up a star badge"
            }
        ]
    elif "share" in title_lower or "sharing" in title_lower or "toy" in title_lower:
        pages = [
            {
                "page_number": 1, 
                "text": f"{intro_prefix}When I am at school, I get to play with many fun toys. Other children like playing with them too.", 
                "visual_prompt": "Two children playing with colorful wooden blocks on a rug"
            },
            {
                "page_number": 2, 
                "text": "Sometimes, another child wants to play with the toy I am holding. Sharing toys is a friendly way to play together.", 
                "visual_prompt": "A child offering a green toy block to a friend who is smiling"
            },
            {
                "page_number": 3, 
                "text": "We can take turns. I can play with the toys first, and then my friend can have a turn. We can use a timer to help us know when to switch.", 
                "visual_prompt": "A sand timer sitting next to building blocks"
            },
            {
                "page_number": 4, 
                "text": "If I want a toy someone else has, I can choose to ask nicely: 'May I play with that when you are done?'. Waiting can feel hard, and I can choose to play with another toy while I wait.", 
                "visual_prompt": "A child asking a friend for a toy while pointing at a coloring book"
            },
            {
                "page_number": 5, 
                "text": "Sharing and taking turns can make my classmates feel happy. Playing together is a fun way to learn and grow.", 
                "visual_prompt": "Group of children holding hands and building a block tower together"
            }
        ]
    else:
        # Improved, specific, and warm custom/generic fallback text
        sit_desc_clean = situation_desc if situation_desc else "trying new experiences and learning new things"
        pages = [
            {
                "page_number": 1, 
                "text": f"{intro_prefix}Today, I am learning about {situation_title}. Exploring new situations is a normal part of my day.", 
                "visual_prompt": f"A cute vector cartoon of a child looking at a path leading to {situation_title}"
            },
            {
                "page_number": 2, 
                "text": f"Here is what happens: {sit_desc_clean}. I can choose to take it one small step at a time.", 
                "visual_prompt": "A simple drawing of stairs with visual progress dots"
            },
            {
                "page_number": 3, 
                "text": "The helpers and family around me want to help me feel comfortable. They feel happy when I choose to ask for help when I need it.", 
                "visual_prompt": "Smiling parents and helpers gesturing warmly and supportively"
            },
            {
                "page_number": 4, 
                "text": "If I feel overwhelmed or notice loud sounds, I can choose to take three slow, deep breaths. This can help my body feel calm inside.", 
                "visual_prompt": "A child taking a deep breath with closed eyes and a peaceful face"
            },
            {
                "page_number": 5, 
                "text": "By doing my best, I can learn how to handle new experiences. I can feel proud of trying new things.", 
                "visual_prompt": "A child smiling and holding a shiny star balloon"
            }
        ]
        
    # Append a personalization slide if key details or special interests are present
    if request.key_details:
        pages.append({
            "page_number": len(pages) + 1,
            "text": f"To help me stay calm and happy, I can choose to think about or use: {request.key_details}.",
            "visual_prompt": "A bright cloud containing images of peaceful and happy things"
        })

    return schemas.StoryCreate(
        title=title,
        situation_id=request.situation_id,
        generation_source=source,
        content=[schemas.StoryPage(**p) for p in pages]
    )

def generate_social_story(db: Session, request: schemas.StoryGenerateRequest) -> schemas.StoryCreate:
    # 1. Retrieve or define situation info
    situation_title = "New Situation"
    situation_desc = ""
    
    if request.situation_id:
        db_situation = db.query(models.Situation).filter(models.Situation.id == request.situation_id).first()
        if db_situation:
            situation_title = db_situation.title
            situation_desc = db_situation.description
            
    if request.custom_situation_text:
        # If both are provided, let's use the custom text as description
        if not request.situation_id:
            situation_title = "Custom Situation"
        situation_desc = request.custom_situation_text

    if request.custom_title:
        situation_title = request.custom_title

    # 2. Check if Gemini API key is missing or set to placeholder
    api_key = os.getenv("GEMINI_API_KEY")
    is_missing = not api_key or api_key == "YOUR_API_KEY_HERE" or api_key.strip() == ""

    if is_missing:
        logger.warning("[AI Service] GEMINI_API_KEY is not configured or set to placeholder. Using fallback/mock generation mode.")
        return _generate_mock_social_story(db, request, source="fallback")

    # 3. Live Gemini API Generation
    child_name = request.child_name
    child_age = request.child_age
    key_details = request.key_details

    prompt_details = ""
    if child_name:
        prompt_details += f"- Personalize the story by introducing the child at the beginning (e.g., 'My name is {child_name}.').\n"
    if child_age:
        prompt_details += f"- The child's age is {child_age}. Ensure the vocabulary, sentence length, and reading level are highly appropriate for a {child_age}-year-old child.\n"
    if key_details:
        prompt_details += f"- Incorporate the child's special details, triggers, interests, and calming tools: '{key_details}'. Weave them naturally and reassuringly into the story narrative as gentle coping options (e.g., 'I can choose to use/think about...' or 'It helps me to...') rather than commands.\n"

    prompt = f"""
You are a friendly educational expert specializing in writing Carol Gray-inspired Social Stories for young children.
Write a personalized, reassuring, and highly predictable Social Story based on these details:
- Story Title Topic: {situation_title}
- Story Scenario: {situation_desc}
- Child's Name: {child_name or "Not specified"}
- Child's Age: {child_age or "Not specified"}
- Child's Details / Triggers / Interests / Calming Tools: {key_details or "None"}

Follow these Carol Gray Social Story Guidelines:
1. First-Person Perspective: The story MUST be written entirely from the child's point of view using first-person pronouns: "I", "my", "me", "we", "our". Do NOT write in the second or third person. Even if the child's name is provided, refer to yourself as "I" or "me" (e.g., "My name is {child_name or 'I'}. Today I am going to...").
2. Simple, Literal, & Reassuring Language: Keep sentences short, concrete, and literal. Avoid all abstract metaphors, idioms, figures of speech, or sarcasm. Ensure the tone is calm, warm, and highly predictable.
3. Descriptive & Perspective Sentences:
   - Descriptive sentences: Describe objectively what is happening, where it is, and who is there (e.g., "The dentist clinic has a big chair. The dentist works there.").
   - Perspective sentences: Describe the thoughts, feelings, or helpful motivations of other people in a reassuring way (e.g., "The dentist wants to help my teeth stay healthy. This makes them happy.").
4. Gentle Coping Options, NOT Commands: Suggest positive, manageable actions or coping tools the child can take (e.g., raising a hand, taking deep breaths, holding a favorite object). Frame these actions as gentle choices/options (e.g., "I can choose to...", "I can try to...") rather than absolute commands or requirements (do NOT use "I must", "I should", "I have to").
5. Avoid Clinical/Diagnosis Language: Do NOT mention any diagnostic terms, conditions, or labels (such as "autism", "neurodivergence", "ADHD", "sensory overload"). Keep the focus purely on the child's personal experience of the situation.
6. Avoid Promising Outcomes: Do NOT guarantee or promise perfect outcomes (e.g., do NOT write "It will never hurt" or "I will be perfectly happy"). Instead, focus on predictability and support (e.g., "My helpers will be there to support me," "This helps me know what to expect.").
7. Length & Structure:
   - Provide exactly 5 to 7 pages.
   - Each page must contain exactly 2 to 3 short, simple sentences.

You must return valid JSON matching this schema:
{{
  "title": "A calm, child-appropriate title for the story",
  "pages": [
    {{
      "page_number": 1,
      "text": "2-3 short, simple first-person story sentences appropriate for a child.",
      "visual_prompt": "A description of a friendly, calm, flat-vector Scandinavian style illustration matching this page"
    }}
  ]
}}
"""

    try:
        logger.info("[AI Service] Requesting social story generation from Gemini API...")
        # Initialize the client with the api key
        client = genai.Client(api_key=api_key)
        
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                response_schema=StoryResponseSchema,
                temperature=0.2
            )
        )
        
        if not response.text:
            raise RuntimeError("Received empty response from Gemini API.")
            
        story_data = json.loads(response.text)
        title = clean_story_title(story_data.get("title") or situation_title, request, is_gemini_generated=True)
        pages = story_data.get("pages", [])
        
        story_pages = [
            schemas.StoryPage(
                page_number=page.get("page_number", idx + 1),
                text=page.get("text", ""),
                visual_prompt=page.get("visual_prompt", "")
            )
            for idx, page in enumerate(pages)
        ]
        
        if not story_pages:
            raise RuntimeError("Gemini generated a story with no pages.")
            
        logger.info(f"[AI Service] Successfully generated social story '{title}' from Gemini API.")
        return schemas.StoryCreate(
            title=title,
            situation_id=request.situation_id,
            generation_source="gemini",
            content=story_pages
        )
        
    except Exception as e:
        # Fall back to mock story generation on ANY live failure or parse error
        logger.error(f"[AI Service] Gemini AI generation failed: {e}. Falling back to mock generation mode.")
        return _generate_mock_social_story(db, request, source="fallback")
